---
- name: Create command and service template for check_gitlab_scheduler
  hosts: localhost
  gather_facts: false
  module_defaults:
    group/telekom_mms.icinga_director.icinga:
      url: "{{ icinga_url }}"
      url_username: "{{ icinga_user }}"
      url_password: "{{ icinga_pass }}"
      force_basic_auth: "{{ icinga_force_basic_auth | default(omit) }}"
  tasks:
    - name: Create command for check_gitlab_scheduler
      telekom_mms.icinga_director.icinga_command:
        state: present
        object_name: check_gitlab_scheduler
        command: check_gitlab_scheduler.py
        arguments:
          -p:
            required: true
            value: $projectid$
          -s:
            required: true
            value: $schedulerid$
          -t:
            required: true
            value: $token$
          -o:
            required: false
            value: $pending_timeout$
    - name: Create service template for check_gitlab_scheduler
      telekom_mms.icinga_director.icinga_service_template:
        state: present
        object_name: check_gitlab_scheduler
        check_command: "check_gitlab_scheduler"
        check_interval: 5m
